# 分类类别文件路径
classes_path: model_data/voc_classes.txt
# 预训练权重文件路径，为空则不加载
model_path: ''
# 输入的大小
input_shape:
  - 300
  - 300
# anchors大小设置，若识别小物体，建议改小浅层
anchors_size:
  - 30
  - 60
  - 111
  - 162
  - 213
  - 264
  - 315
# 冻结阶段训练参数
Init_Epoch: 0
Freeze_Epoch: 2
Freeze_batch_size: 16
Freeze_lr: 0.0005
# 解冻阶段训练参数
UnFreeze_Epoch: 1
UnFreeze_batch_size: 8
UnFreeze_lr: 0.0001
# 是否进行冻结训练
Freeze_Train: True
# 是否进行多线程，若为0则不开启多线程，>0则开启多少个线程
num_workers: 0
# 训练集图片和标签信息文件路径
train_annotation_path: 2007_train.txt
# 验证集图片和标签信息文件路径
val_annotation_path: 2007_val.txt
